### ISSUE TITLE
Error downloading web worker

### ISSUE THREAD

**Issue by jitenderchand1** [devfd/react-native-workers#14]
I have worker script in same folder in which I have a file in which I am worker js.

//service.js
const worker = new Worker('worker.js');

Both service.js and worker.js is in same folder.

![screen shot 2016-09-27 at 5 09 29 pm](https://cloud.githubusercontent.com/assets/19687185/18871923/6961bcfe-84d5-11e6-9673-46ffc9eb4d31.png)

**Comment by RichardBoyewa** [comment]
@jitenderchand1 Whats your folder structure like?

**Comment by jitenderchand1** [comment]
My folder structure look like.

![screen shot 2016-09-28 at 10 04 34 am](https://cloud.githubusercontent.com/assets/19687185/18901453/b8b028b6-8568-11e6-9e8e-36eb8fca183f.png)

**Code in service.container.js**

```
const worker = new Worker('worker.js');
    //console.log(worker.postMessage)
    worker.postMessage("start");
```

**Code in worker.js**

```
import { self } from 'react-native-workers';
/* get message from application. String only ! */
self.onmessage = (message) => {
}

/* post message to application. String only ! */
self.postMessage("hello from worker");


```

even I am getting this error when using absolute path.

```
const worker = new Worker('http://www.w3schools.com/html/demo_workers.js');
    //console.log(worker.postMessage)
    worker.postMessage("start");
```

**Comment by jitenderchand1** [comment]
fixed

**Comment by StellwagJo** [comment]
Could you please explain us how you fixed this issue. I am using React-Native 0.31 and having the same issue.

**Comment by RichardBoyewa** [comment]
@StellwagJo Setting appropriate path should fix it. Let me know if u still have the problem.

**Comment by StellwagJo** [comment]
Thanks the solution with appropriate path worked for me too.
